In [1]:
#import pandas library
import pandas as pd

## Reading Football match data into dataframe

In [2]:
#Reading Football match data into dataframe

matches=pd.read_csv("C:\\Users\\d3637265\\Downloads\\matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,15/08/2021,16:30,Premier League,Matchweek 1,Sun,partly cloud,Away,L,0,1,...,Match Report,NaN,18,4,16.9,1,0,0,2022,Manchester City
2,21/08/2021,15:00,Premier League,Matchweek 2,Sat,sunny,Home,W,5,0,...,Match Report,NaN,16,4,17.3,1,0,0,2022,Manchester City
3,28/08/2021,12:30,Premier League,Matchweek 3,Sat,sunny,Home,W,5,0,...,Match Report,NaN,25,10,14.3,0,0,0,2022,Manchester City
4,11/09/2021,15:00,Premier League,Matchweek 4,Sat,partly cloud,Away,W,1,0,...,Match Report,NaN,25,8,14.0,0,0,0,2022,Manchester City
6,18/09/2021,15:00,Premier League,Matchweek 5,Sat,partly cloud,Home,D,0,0,...,Match Report,NaN,16,1,15.7,1,0,0,2022,Manchester City

In [4]:
#shape property for rows and coloumns
matches.shape

(1389, 28)

## Investigating missing data

In [5]:
# 2 seasons * 20 squads * 38 matches

2 * 20 * 38

1520

In [6]:
# Missing Liverpool 2021-2022

matches["team"].value_counts()

Southampton                 72
Brighton and Hove Albion    72
Manchester United           72
West Ham United             72
Newcastle United            72
Burnley                     71
Leeds United                71
Crystal Palace              71
Manchester City             71
Wolverhampton Wanderers     71
Tottenham Hotspur           71
Arsenal                     71
Leicester City              70
Chelsea                     70
Aston Villa                 70
Everton                     70
Liverpool                   38
Fulham                      38
West Bromwich Albion        38
Sheffield United            38
Brentford                   34
Watford                     33
Norwich City                33
Name: team, dtype: int64

In [7]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
32,03/02/2021,20:15,Premier League,Matchweek 22,Wed,rainy,Home,L,0,1,...,Match Report,NaN,11,0,19.9,0,0,0,2021,Liverpool
42,03/04/2021,20:00,Premier League,Matchweek 30,Sat,rainy,Away,W,3,0,...,Match Report,NaN,16,7,17.0,0,0,0,2021,Liverpool
25,04/01/2021,20:00,Premier League,Matchweek 17,Mon,sunny,Away,L,0,1,...,Match Report,NaN,17,1,14.3,0,0,0,2021,Liverpool
38,04/03/2021,20:15,Premier League,Matchweek 29,Thu,sunny,Home,L,0,1,...,Match Report,NaN,7,1,18.4,0,0,0,2021,Liverpool
6,04/10/2020,19:15,Premier League,Matchweek 4,Sun,sunny,Away,L,2,7,...,Match Report,NaN,14,8,15.8,1,0,0,2021,Liverpool
18,06/12/2020,19:15,Premier League,Matchweek 11,Sun,partly cloud,Home,W,4,0,...,Match Report,NaN,11,6,16.6,1,0,0,2021,Liverpool
33,07/02/2021,16:30,Premier League,Matchweek 23,Sun,cloudy,Home,L,1,4,...,Match Report,NaN,7,2,17.9,1,1,1,2021,Liverpool
39,07/03/2021,14:00,Premier League,Matchweek 27,Sun,partly cloud,Home,L,0,1,...,Match Report,NaN,16,3,17.0,1,0,0,2021,Liverpool
48,08/05/2021,20:15,Premier League,Matchweek 35,Sat,rainy,Home,W,2,0,...,Match Report,NaN,14,6,12.4,0,0,0,2021,Liverpool
13,08/11/2020,16:30,Premier League,Matchweek 8,Sun,sunny,Away,D,1,1,...,Match Report,NaN,9,2,21.5,0,1,1,2021,Liverpool
44,10/04/2021,15:00,Premier League,Matchweek 31,Sat,sunny,Home,W,2,1,...,Match Report,NaN,23,8,16.7,1,0,0,2021,Liverpool
1,12/09/2020,17:30,Premier League,Matchweek 1,Sat,partly cloud,Home,W,4,3,...,Match Report,NaN,20,4,17.0,0,2,2,2021,Liverpool
34,13/02/2021,12:30,Premier League,Matchweek 24,Sat,cloudy,Away,L,1,3,...,Match Report,NaN,15,4,15.4,2,0,0,2021,Liverpool
49,13/05/2021,20:15,Premier League,Matchweek 34,Thu,cloudy,Away,W,4,2,...,Match Report,NaN,17,8,14.9,0,0,0,2021,Liverpool
20,13/12/2020,16:30,Premier League,Matchweek 12,Sun,partly cloud,Away,D,1,1,...,Match Report,NaN,11,5,20.0,1,1,1,2021,Liverpool
41,15/03/2021,20:00,Premier League,Matchweek 28,Mon,partly cloud,Away,W,1,0,...,Match Report,NaN,12,4,15.9,0,0,0,2021,Liverpool
50,16/05/2021,16:30,Premier League,Matchweek 36,Sun,cloudy,Away,W,2,1,...,Match Report,NaN,26,6,16.9,1,0,0,2021,Liverpool
21,16/12/2020,20:00,Premier League,Matchweek 13,Wed,sunny,Home,W,2,1,...,Match Report,NaN,17,11,15.5,0,0,0,2021,Liverpool
27,17/01/2021,16:30,Premier League,Matchweek 19,Sun,cloudy,Home,D,0,0,...,Match Report,NaN,17,3,17.1,0,0,0,2021,Liverpool
7,17/10/2020,12:30,Premier League,Matchweek 5,Sat,cloudy,Away,D,2,2,...,Match Report,NaN,22,8,15.0,1,0,0,2021,Liverpool
46,19/04/2021,20:00,Premier League,Matchweek 32,Mon,rainy,Away,D,1,1,...,Match Report,NaN,17,7,15.7,0,0,0,2021,Liverpool
51,19/05/2021,20:15,Premier League,Matchweek 37,Wed,partly cloud,Away,W,3,0,...,Match Report,NaN,20,3,15.5,1,0,0,2021,Liverpool
22,19/12/2020,12:30,Premier League,Matchweek 14,Sat,sunny,Away,W,7,0,...,Match Report,NaN,14,7,13.2,1,0,0,2021,Liverpool
36,20/02/2021,17:30,Premier League,Matchweek 25,Sat,sunny,Home,L,0,2,...,Match Report,NaN,16,6,15.9,1,0,0,2021,Liverpool
2,20/09/2020,16:30,Premier League,Matchweek 2,Sun,cloudy,Away,W,2,0,...,Match Report,NaN,17,5,17.7,1,0,0,2021,Liverpool
28,21/01/2021,20:00,Premier League,Matchweek 18,Thu,partly cloud,Home,L,0,1,...,Match Report,NaN,27,6,17.3,0,0,0,2021,Liverpool
14,22/11/2020,19:15,Premier League,Matchweek 9,Sun,sunny,Home,W,3,0,...,Match Report,NaN,24,12,11.9,0,0,0,2021,Liverpool
52,23/05/2021,16:00,Premier League,Matchweek 38,Sun,partly cloud,Home,W,2,0,...,Match Report,NaN,19,5,14.2,1,0,0,2021,Liverpool
47,24/04/2021,12:30,Premier League,Matchweek 33,Sat,rainy,Home,D,1,1,...,Match Report,NaN,21,9,17.0,1,0,0,2021,Liverpool
9,24/10/2020,20:00,Premier League,Matchweek 6,Sat,cloudy,Home,W,2,1,...,Match Report,NaN,17,5,18.2,1,0,0,2021,Liverpool
23,27/12/2020,16:30,Premier League,Matchweek 15,Sun,partly cloud,Home,D,1,1,...,Match Report,NaN,17,2,17.8,2,0,0,2021,Liverpool
30,28/01/2021,20:00,Premier League,Matchweek 20,Thu,sunny,Away,W,3,1,...,Match Report,NaN,14,7,14.7,0,0,0,2021,Liverpool
37,28/02/2021,19:15,Premier League,Matchweek 26,Sun,sunny,Away,W,2,0,...,Match Report,NaN,15,8,14.2,0,0,0,2021,Liverpool
4,28/09/2020,20:00,Premier League,Matchweek 3,Mon,cloudy,Home,W,3,1,...,Match Report,NaN,21,9,16.8,0,0,0,2021,Liverpool
16,28/11/2020,12:30,Premier League,Matchweek 10,Sat,partly cloud,Away,D,1,1,...,Match Report,NaN,6,2,20.9,0,0,0,2021,Liverpool
24,30/12/2020,20:00,Premier League,Matchweek 16,Wed,partly cloud,Away,D,0,0,...,Match Report,NaN,11,4,16.7,0,0,0,2021,Liverpool
31,31/01/2021,16:30,Premier League,Matchweek 21,Sun,sunny,Away,W,3,1,...,Match Report,NaN,14,5,15.3,0,0,0,2021,Liverpool
11,31/10/2020,17:30,Premier League,Matchweek 7,Sat,cloudy,Home,W,2,1,...,Match Report,NaN,8,2,18.6,1,1,1,2021,Liverpool

In [8]:
matches["round"].value_counts()

Matchweek 1     39
Matchweek 16    39
Matchweek 34    39
Matchweek 32    39
Matchweek 31    39
Matchweek 29    39
Matchweek 28    39
Matchweek 26    39
Matchweek 25    39
Matchweek 24    39
Matchweek 23    39
Matchweek 2     39
Matchweek 19    39
Matchweek 17    39
Matchweek 20    39
Matchweek 15    39
Matchweek 5     39
Matchweek 3     39
Matchweek 13    39
Matchweek 12    39
Matchweek 4     39
Matchweek 11    39
Matchweek 10    39
Matchweek 9     39
Matchweek 8     39
Matchweek 14    39
Matchweek 7     39
Matchweek 6     39
Matchweek 30    37
Matchweek 27    37
Matchweek 22    37
Matchweek 21    37
Matchweek 18    37
Matchweek 33    32
Matchweek 35    20
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: round, dtype: int64

## Cleaning data for machine learning

In [9]:
matches.dtypes # checking datatype for each coloumn, ML algorithm can't work with object data

date             object
time             object
comp             object
round            object
day              object
wheather         object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss              int64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh                int64
sot               int64
dist            float64
fk                int64
pk                int64
pkatt             int64
season            int64
team             object
dtype: object

In [48]:
#converting the date coloumn string into datatype

matches["date"]=pd.to_datetime(matches["date"])

In [49]:
matches.dtypes #the date coloumn datatype is changed

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
wheather                object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                     int64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                       int64
sot                      int64
dist                   float64
fk                       int64
pk                       int64
pkatt                    int64
season                   int64
team                    object
venue_code                int8
opp_code                  int8
hour                     int32
day_code                 int64
target                   int32
dtype: object

## Creating predictors for machine learning

In [12]:
# we need venue coloumn as a numbers,so we convert string into category and then to numbers

matches["venue_code"]=matches["venue"].astype("category").cat.codes

In [13]:
matches #here in venuecode '0' indicates away and '1' indicates home match

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,venue_code
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,partly cloud,Away,L,0,1,...,NaN,18,4,16.9,1,0,0,2022,Manchester City,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,sunny,Home,W,5,0,...,NaN,16,4,17.3,1,0,0,2022,Manchester City,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,sunny,Home,W,5,0,...,NaN,25,10,14.3,0,0,0,2022,Manchester City,1
4,2021-11-09,15:00,Premier League,Matchweek 4,Sat,partly cloud,Away,W,1,0,...,NaN,25,8,14.0,0,0,0,2022,Manchester City,0
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,partly cloud,Home,D,0,0,...,NaN,16,1,15.7,1,0,0,2022,Manchester City,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-02-05,19:15,Premier League,Matchweek 34,Sun,partly cloud,Away,L,0,4,...,NaN,8,1,17.4,0,0,0,2021,Sheffield United,0
39,2021-08-05,15:00,Premier League,Matchweek 35,Sat,partly cloud,Home,L,0,2,...,NaN,7,0,11.4,1,0,0,2021,Sheffield United,1
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,rainy,Away,W,1,0,...,NaN,10,3,17.0,0,0,0,2021,Sheffield United,0
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,rainy,Away,L,0,1,...,NaN,11,1,16.0,1,0,0,2021,Sheffield United,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,sunny,Home,W,1,0,...,NaN,12,3,17.0,0,0,0,2021,Sheffield United,1

In [14]:
#generating a unique code for the opponents same as we did before

matches["opp_code"]=matches["opponent"].astype("category").cat.codes

In [15]:
#convert the hour coloumn to an integer using regular expression, so that we use number as input in ML 
matches["hour"]=matches["time"].str.replace(":.+","",regex="true").astype("int")

In [16]:
# we create a day_code coloumn to generate a number for a day coloumn
matches["day_code"]=matches["date"].dt.dayofweek #using dayofweek property we get a number for particular day in week

In [17]:
# creating a number for a result coloumn using true false expression
matches["target"]=(matches["result"]=="W").astype("int")

In [18]:
#In hour and opp_code coloumn we can see the number
#In daycode we got no of day of each week
matches

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,partly cloud,Away,L,0,1,...,1,0,0,2022,Manchester City,0,18,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,sunny,Home,W,5,0,...,1,0,0,2022,Manchester City,1,15,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,sunny,Home,W,5,0,...,0,0,0,2022,Manchester City,1,0,12,5,1
4,2021-11-09,15:00,Premier League,Matchweek 4,Sat,partly cloud,Away,W,1,0,...,0,0,0,2022,Manchester City,0,10,15,1,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,partly cloud,Home,D,0,0,...,1,0,0,2022,Manchester City,1,17,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-02-05,19:15,Premier League,Matchweek 34,Sun,partly cloud,Away,L,0,4,...,0,0,0,2021,Sheffield United,0,18,19,4,0
39,2021-08-05,15:00,Premier League,Matchweek 35,Sat,partly cloud,Home,L,0,2,...,1,0,0,2021,Sheffield United,1,6,15,3,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,rainy,Away,W,1,0,...,0,0,0,2021,Sheffield United,0,7,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,rainy,Away,L,0,1,...,1,0,0,2021,Sheffield United,0,14,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,sunny,Home,W,1,0,...,0,0,0,2021,Sheffield United,1,4,16,6,1

## Creating initial machine learning model

In [19]:
#it's ready to train our ml model
#importing random forestclassifier model they can pickup non-linearities in data
from sklearn.ensemble import RandomForestClassifier

In [20]:
#initializing rfc class by passing parameters
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1) #set a no of decision tree value

In [21]:
train = matches[matches["date"] < '2022-01-01']

In [22]:
test = matches[matches["date"] > '2022-01-01']

In [23]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [24]:
rf.fit(train[predictors], train["target"]) #.fit method trains rf models using predictors

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [25]:
preds = rf.predict(test[predictors]) #generating prediction by passing test data

In [26]:
#import accuracy_score librabry to get accurate results
from sklearn.metrics import accuracy_score

In [27]:
acc = accuracy_score(test["target"], preds)

In [28]:
acc #when we predicted something would happen 61 of the time that thing happened

0.605072463768116

In [29]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds)) #created a df that would combine actual and predicted values

In [30]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"]) #created a crosstab using pd, it's a 2 way table that shows whenn we predict 0 or 1  what's the  actual percentage

prediction    0   1
actual
0           146  26
1            83  21

In [31]:
from sklearn.metrics import precision_score

In [32]:
precision_score(test["target"],preds) #it shows the actual percentage of time based on what we have predicted

0.44680851063829785

# Improving precision with rolling averages

In [33]:
grouped_matches = matches.groupby("team") #creates a one df for every squad in data

In [34]:
group = grouped_matches.get_group("Manchester City").sort_values("date") #it gives a single group from data

In [35]:
group

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
4,2020-03-10,17:30,Premier League,Matchweek 4,Sat,sunny,Away,D,1,1,...,1,0,0,2021,Manchester City,0,9,17,1,0
16,2020-05-12,15:00,Premier League,Matchweek 11,Sat,sunny,Home,W,2,0,...,0,1,1,2021,Manchester City,1,8,15,1,1
11,2020-08-11,16:30,Premier League,Matchweek 8,Sun,cloudy,Home,D,1,1,...,0,0,1,2021,Manchester City,1,11,16,1,0
0,2020-09-21,20:15,Premier League,Matchweek 2,Mon,sunny,Away,W,3,1,...,2,1,1,2021,Manchester City,0,22,20,0,1
2,2020-09-27,16:30,Premier League,Matchweek 3,Sun,sunny,Home,L,2,5,...,1,0,0,2021,Manchester City,1,10,16,6,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,partly cloud,Home,W,5,1,...,0,1,1,2022,Manchester City,1,19,15,5,1
40,2022-06-03,16:30,Premier League,Matchweek 28,Sun,sunny,Home,W,4,1,...,1,0,0,2022,Manchester City,1,13,16,4,1
34,2022-09-02,19:45,Premier League,Matchweek 24,Wed,cloudy,Home,W,2,0,...,0,1,1,2022,Manchester City,1,2,19,4,1
46,2022-10-04,16:30,Premier League,Matchweek 32,Sun,sunny,Home,D,2,2,...,1,0,0,2022,Manchester City,1,11,16,1,0
35,2022-12-02,17:30,Premier League,Matchweek 25,Sat,cloudy,Away,W,4,0,...,0,0,1,2022,Manchester City,0,15,17,4,1

In [36]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group #this fun will take a set of coloumns to compute rolling averages for and then it'll take in a set of new coloumns that we want to assign the rolling averages

In [37]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

new_cols #cloumns list to compute rolling averages for

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [38]:
rolling_averages(group, cols, new_cols) #for the new coloumns that have info about what happened inthe last 3 matches

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-09-21,20:15,Premier League,Matchweek 2,Mon,sunny,Away,W,3,1,...,0,1,1.333333,0.666667,14.666667,2.666667,17.700000,0.333333,0.333333,0.666667
2,2020-09-27,16:30,Premier League,Matchweek 3,Sun,sunny,Home,L,2,5,...,6,0,2.000000,0.666667,11.333333,5.000000,18.600000,0.666667,0.666667,1.000000
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,cloudy,Home,W,1,0,...,5,1,2.000000,2.333333,11.666667,5.000000,19.533333,1.000000,0.333333,0.666667
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,cloudy,Away,D,1,1,...,5,0,2.000000,2.000000,14.000000,6.000000,18.633333,1.000000,0.333333,0.333333
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,cloudy,Away,W,1,0,...,5,1,1.333333,2.000000,14.333333,5.666667,18.633333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,partly cloud,Home,W,5,1,...,5,1,1.333333,0.000000,16.000000,5.666667,17.400000,0.000000,0.000000,0.000000
40,2022-06-03,16:30,Premier League,Matchweek 28,Sun,sunny,Home,W,4,1,...,4,1,2.666667,0.333333,18.333333,5.333333,17.066667,0.000000,0.333333,0.333333
34,2022-09-02,19:45,Premier League,Matchweek 24,Wed,cloudy,Home,W,2,0,...,4,1,4.000000,0.666667,20.333333,7.333333,16.166667,0.333333,0.333333,0.333333
46,2022-10-04,16:30,Premier League,Matchweek 32,Sun,sunny,Home,D,2,2,...,1,0,3.666667,0.666667,19.333333,7.666667,16.100000,0.333333,0.666667,0.666667
35,2022-12-02,17:30,Premier League,Matchweek 25,Sat,cloudy,Away,W,4,0,...,4,1,2.666667,1.000000,16.333333,6.666667,16.700000,0.666667,0.333333,0.333333

In [39]:
#apply this to all the our matches
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols)) #applied func to each of those team df

In [40]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 13 2020-08-11  19:15  Premier League   Matchweek 8
                        2  2020-09-19  20:00  Premier League   Matchweek 2
                        4  2020-09-28  20:00  Premier League   Matchweek 3
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
...                               ...    ...             ...           ...
Wolverhampton Wanderers 36 2022-04-24  14:00  Premier League  Matchweek 34
                        30 2022-05-03  15:00  Premier League  Matchweek 28
                        35 2022-08-04  20:00  Premier League  Matchweek 32
                        25 2022-10-02  19:45  Premier League  Matchweek 24
                        31 2022-10-03  19:30  Premier League  Matchweek 19

                            day      wheather venue result  gf  ga  ...  \
team                                                                ...
Arsenal                 13  Sun  partly cloud  Home      L   0   3  ...
                        2   Sat         sunny  Home      W   2   1  ...
                        4   Mon         sunny  Away      L   1   3  ...
                        7   Sat  partly cloud  Away      L   0   1  ...
                        9   Sun         sunny  Home      L   0   1  ...
...                         ...           ...   ...    ...  ..  ..  ...
Wolverhampton Wanderers 36  Sun         sunny  Away      L   0   1  ...
                        30  Sat        cloudy  Home      L   0   2  ...
                        35  Fri         sunny  Away      L   0   1  ...
                        25  Thu         sunny  Home      L   0   1  ...
                        31  Thu        cloudy  Home      W   4   0  ...

                           day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 13        1       0    1.000000    1.000000
                        2         5       1    0.666667    2.000000
                        4         0       0    0.666667    2.000000
                        7         5       0    1.000000    2.333333
                        9         6       0    1.000000    1.666667
...                             ...     ...         ...         ...
Wolverhampton Wanderers 36        6       0    1.333333    1.000000
                        30        1       0    1.000000    1.333333
                        35        3       0    0.666667    2.000000
                        25        6       0    0.000000    1.333333
                        31        0       1    0.000000    1.333333

                            sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 13    8.000000    2.666667    18.166667   0.333333
                        2    10.333333    3.000000    15.800000   0.333333
                        4    10.333333    2.333333    15.333333   0.333333
                        7     7.666667    2.666667    15.400000   0.000000
                        9     7.000000    3.000000    16.266667   0.666667
...                                ...         ...          ...        ...
Wolverhampton Wanderers 36   15.666667    5.666667    20.333333   0.333333
                        30   12.666667    5.000000    19.966667   0.000000
                        35   12.000000    5.666667    19.700000   0.000000
                        25    9.000000    3.666667    18.833333   0.000000
                        31   10.666667    3.666667    18.866667   0.666667

                           pk_rolling  pkatt_rolling
team
Arsenal                 13   0.333333       0.333333
                        2    0.000000       0.000000
                        4    0.000000       0.000000
                        7    0.000000       0.000000
                        9    0.000000       0.000000
...                               ...            ...
Wolverhampton Wanderers 36   0.000000       0.000000
                        30   0.000000       0.000000
                        35   0.000000       0.000000
                        25   0.000000       0.000000
                        31   0.000000       0.000000

[1317 rows x 41 columns]

In [41]:
matches_rolling = matches_rolling.droplevel('team') #this drops the extra index level from above

In [42]:
matches_rolling

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
13,2020-08-11,19:15,Premier League,Matchweek 8,Sun,partly cloud,Home,L,0,3,...,1,0,1.000000,1.000000,8.000000,2.666667,18.166667,0.333333,0.333333,0.333333
2,2020-09-19,20:00,Premier League,Matchweek 2,Sat,sunny,Home,W,2,1,...,5,1,0.666667,2.000000,10.333333,3.000000,15.800000,0.333333,0.000000,0.000000
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,sunny,Away,L,1,3,...,0,0,0.666667,2.000000,10.333333,2.333333,15.333333,0.333333,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,partly cloud,Away,L,0,1,...,5,0,1.000000,2.333333,7.666667,2.666667,15.400000,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,sunny,Home,L,0,1,...,6,0,1.000000,1.666667,7.000000,3.000000,16.266667,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2022-04-24,14:00,Premier League,Matchweek 34,Sun,sunny,Away,L,0,1,...,6,0,1.333333,1.000000,15.666667,5.666667,20.333333,0.333333,0.000000,0.000000
30,2022-05-03,15:00,Premier League,Matchweek 28,Sat,cloudy,Home,L,0,2,...,1,0,1.000000,1.333333,12.666667,5.000000,19.966667,0.000000,0.000000,0.000000
35,2022-08-04,20:00,Premier League,Matchweek 32,Fri,sunny,Away,L,0,1,...,3,0,0.666667,2.000000,12.000000,5.666667,19.700000,0.000000,0.000000,0.000000
25,2022-10-02,19:45,Premier League,Matchweek 24,Thu,sunny,Home,L,0,1,...,6,0,0.000000,1.333333,9.000000,3.666667,18.833333,0.000000,0.000000,0.000000
31,2022-10-03,19:30,Premier League,Matchweek 19,Thu,cloudy,Home,W,4,0,...,0,1,0.000000,1.333333,10.666667,3.666667,18.866667,0.666667,0.000000,0.000000

In [43]:
#there are some repeated values in index, we want unique values from index
matches_rolling.index = range(matches_rolling.shape[0]) #thus will assign values from 0 to 1316

In [44]:
matches_rolling #we get a new indicies, that gives unique values for each index

,date,time,comp,round,day,wheather,venue,result,gf,ga,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-08-11,19:15,Premier League,Matchweek 8,Sun,partly cloud,Home,L,0,3,...,1,0,1.000000,1.000000,8.000000,2.666667,18.166667,0.333333,0.333333,0.333333
1,2020-09-19,20:00,Premier League,Matchweek 2,Sat,sunny,Home,W,2,1,...,5,1,0.666667,2.000000,10.333333,3.000000,15.800000,0.333333,0.000000,0.000000
2,2020-09-28,20:00,Premier League,Matchweek 3,Mon,sunny,Away,L,1,3,...,0,0,0.666667,2.000000,10.333333,2.333333,15.333333,0.333333,0.000000,0.000000
3,2020-10-17,17:30,Premier League,Matchweek 5,Sat,partly cloud,Away,L,0,1,...,5,0,1.000000,2.333333,7.666667,2.666667,15.400000,0.000000,0.000000,0.000000
4,2020-10-25,19:15,Premier League,Matchweek 6,Sun,sunny,Home,L,0,1,...,6,0,1.000000,1.666667,7.000000,3.000000,16.266667,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,2022-04-24,14:00,Premier League,Matchweek 34,Sun,sunny,Away,L,0,1,...,6,0,1.333333,1.000000,15.666667,5.666667,20.333333,0.333333,0.000000,0.000000
1313,2022-05-03,15:00,Premier League,Matchweek 28,Sat,cloudy,Home,L,0,2,...,1,0,1.000000,1.333333,12.666667,5.000000,19.966667,0.000000,0.000000,0.000000
1314,2022-08-04,20:00,Premier League,Matchweek 32,Fri,sunny,Away,L,0,1,...,3,0,0.666667,2.000000,12.000000,5.666667,19.700000,0.000000,0.000000,0.000000
1315,2022-10-02,19:45,Premier League,Matchweek 24,Thu,sunny,Home,L,0,1,...,6,0,0.000000,1.333333,9.000000,3.666667,18.833333,0.000000,0.000000,0.000000
1316,2022-10-03,19:30,Premier League,Matchweek 19,Thu,cloudy,Home,W,4,0,...,0,1,0.000000,1.333333,10.666667,3.666667,18.866667,0.666667,0.000000,0.000000

# Retraining ML model

In [50]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [54]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [55]:
precision

0.6

In [56]:
combined

      actual  predicted
55         0          1
56         1          0
57         1          1
58         1          0
59         0          0
...      ...        ...
1312       0          0
1313       0          0
1314       0          0
1315       0          0
1316       1          0

[276 rows x 2 columns]

In [57]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [58]:
combined

,actual,predicted,date,team,opponent,result
55,0,1,2022-01-23,Arsenal,Burnley,D
56,1,0,2022-02-19,Arsenal,Brentford,W
57,1,1,2022-02-24,Arsenal,Wolves,W
58,1,0,2022-03-13,Arsenal,Leicester City,W
59,0,0,2022-03-16,Arsenal,Liverpool,L
...,...,...,...,...,...,...
1312,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L
1313,0,0,2022-05-03,Wolverhampton Wanderers,Crystal Palace,L
1314,0,0,2022-08-04,Wolverhampton Wanderers,Newcastle Utd,L
1315,0,0,2022-10-02,Wolverhampton Wanderers,Arsenal,L
1316,1,0,2022-10-03,Wolverhampton Wanderers,Watford,W

# Combining home and away predictions

In [60]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", 
              "Manchester United": "Manchester Utd", 
              "Newcastle United": "Newcastle Utd", 
              "Tottenham Hotspur": "Tottenham", 
              "West Ham United": "West Ham", 
              "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [61]:
mapping["West Ham United"]

'West Ham'

In [62]:
combined["new_team"] = combined["team"].map(mapping)

In [64]:
combined

,actual,predicted,date,team,opponent,result,new_team
55,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal
56,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
57,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
58,1,0,2022-03-13,Arsenal,Leicester City,W,Arsenal
59,0,0,2022-03-16,Arsenal,Liverpool,L,Arsenal
...,...,...,...,...,...,...,...
1312,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves
1313,0,0,2022-05-03,Wolverhampton Wanderers,Crystal Palace,L,Wolves
1314,0,0,2022-08-04,Wolverhampton Wanderers,Newcastle Utd,L,Wolves
1315,0,0,2022-10-02,Wolverhampton Wanderers,Arsenal,L,Wolves
1316,1,0,2022-10-03,Wolverhampton Wanderers,Watford,W,Wolves

In [65]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [66]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
2,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
3,1,0,2022-03-13,Arsenal,Leicester City,W,Arsenal,0,0,Leicester City,Arsenal,L,Leicester City
4,1,0,2022-03-19,Arsenal,Aston Villa,W,Arsenal,0,0,Aston Villa,Arsenal,L,Aston Villa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley
258,0,0,2022-05-03,Wolverhampton Wanderers,Crystal Palace,L,Wolves,1,0,Crystal Palace,Wolves,W,Crystal Palace
259,0,0,2022-08-04,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,1,Newcastle United,Wolves,W,Newcastle Utd
260,0,0,2022-10-02,Wolverhampton Wanderers,Arsenal,L,Wolves,1,1,Arsenal,Wolves,W,Arsenal
261,1,0,2022-10-03,Wolverhampton Wanderers,Watford,W,Wolves,0,0,Watford,Wolves,L,Watford

In [70]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    23
0    13
Name: actual_x, dtype: int64

In [68]:
23/40

0.575